#!/usr/bin/python2

import argparse
from pstor.commands import cmd_list
from pstor.helpers.exceptions import PstorException

def main():
    #http://stackoverflow.com/questions/9729919/gem-git-style-command-line-arguments-in-python
    #http://code.google.com/p/crypt-manager/source/browse/trunk/conceal/conceal.py
    parser = argparse.ArgumentParser(description='PStor - Encrypted storage manager')
    subparsers = parser.add_subparsers(dest='sub_commands')
    init = subparsers.add_parser('init')
    init.add_argument('--pass')
    subparsers.add_parser('status')
    destroy = subparsers.add_parser('destroy')
    destroy.add_argument('--force', action="store_true", default=False)
    subparsers.add_parser('remote')
    up = subparsers.add_parser('up')
    up.add_argument('--pass')
    subparsers.add_parser('down')
    args = parser.parse_args()
    # print vars(args)
    try:
        cmd_list[args.sub_commands] (**vars(args))
    except PstorException, e:
        print e.message

if __name__ == '__main__':
    main()